/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./grammar.macro.js#8d55770348dc7618722d5694771d9ba593f25914
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
let _initProto;
import { re } from '@bablr/boot';
import { eat } from '@bablr/helpers/grammar';
import { Node } from '@bablr/helpers/decorators';
export const canonicalURL = 'https://bablr.org/languages/core/en/space-tab-newline';
export const grammar = class BlankSpaceGrammar {
  static {
    [_initProto] = _applyDecs(this, [[Node, 2, "Space"]], []).e;
  }
  constructor() {
    _initProto(this);
  }
  *Space() {
    yield eat(re`/[ \t\r\n]+/`);
  }
};