/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./grammar.macro.js#1453c6c6c016f47cabcb783118d81ac82d4aa22e
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
let _initProto;
import { re, spam as m } from '@bablr/boot';
import { o, eat, match, eatMatch } from '@bablr/helpers/grammar';
import { Node } from '@bablr/helpers/decorators';
export const canonicalURL = 'https://bablr.org/languages/core/en/space-tab-newline';
export const grammar = class BlankSpaceGrammar {
  static {
    [_initProto] = _applyDecs(this, [[Node, 2, "Space"], [Node, 2, "LeftOffset"], [Node, 2, "Newline"], [Node, 2, "Indent"]], []).e;
  }
  constructor() {
    _initProto(this);
  }
  *Blank() {
    while (yield match(re`/[ \t\r\n]/`)) {
      if (yield match(re`/^/m`)) {
        yield eatMatch(m`<LeftOffset />`);
        yield eatMatch(m`<*Space />`, o({
          only: true
        }));
      } else if (yield match(re`/[\r\n]/`)) {
        yield eat(m`<*Newline />`);
      } else {
        yield eat(m`<*Space />`, o({
          only: true
        }));
      }
    }
  }
  *Space({
    props: {
      only
    }
  }) {
    if (only) {
      yield eat(re`/[ \t]+/`);
    } else {
      yield eat(re`/[ \t\r\n]+/`);
    }
  }
  *LeftOffset() {
    while (yield eatMatch(m`indents[]: <*Indent /\t|  / />`));
  }
  *Newline() {
    yield eat(re`/\r?\n?/`);
  }
  *Indent() {
    yield eat(re`/\t|  /`);
  }
};